### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by sbaber82** [MicrosoftDocs/OfficeDocs-FastTrack#1]
The FastTrack site link is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea39608-d211-6515-b8b8-4f65397b7915
* Version Independent ID: 52863af5-d6b7-4bb3-75bc-a2b0aa0bcf11
* Content: [The FastTrack Process](https://docs.microsoft.com/en-us/fasttrack/o365-fasttrack-process)
* Content Source: [fasttrack/O365-fasttrack-process.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/O365-fasttrack-process.md)
* Service: **o365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Link is performing as expected. Closing issue.
