### ISSUE TITLE
FastTrack service description for Windows 10 is missing "FastTrack responsibilities" section

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/OfficeDocs-FastTrack#10]
FastTrack service descriptions for Office 365 and EMS have a "FastTrack responsibilities" section, but there's no such section for Windows 10. So, if a customer wants to know what to expect from FT W10 they have a more difficult time than for O365, e.g.

**Comment by v-rberg-MSFT** [comment]
Jordi,

I have brought up your feedback to the stakeholders. As soon as I hear from them, I'll let you know.
Thanks!

Ryan

**Comment by v-rberg-MSFT** [comment]
Jordi,

There are plans for such a section. Implementation and publication are still TBD.
Thanks for your feedback!

Ryan
