### ISSUE TITLE
FastTrack Assistance and Volume Licensing

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-FastTrack#11]
Volume Licensing subscriptions are typically excluded from FastTrack Eligible plans, operationally, but the documentation does not reflect this. This is of particular importance for services like Windows 10 and Office ProPlus. The documentation should indicate that volume licensed subscriptions are not eligible for FastTrack assistance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f59014-c8c8-08e9-6304-d1d30f0fbda8
* Version Independent ID: 5317aa75-852e-14bc-0f17-8e3ad03349f7
* Content: [Eligible Services and Plans](https://docs.microsoft.com/en-us/fasttrack/m365-eligible-services-and-plans)
* Content Source: [fasttrack/M365-eligible-services-and-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/M365-eligible-services-and-plans.md)
* Service: **m365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Oliver,

I've heard back from our SMEs:

"The SD is clear that customers need a license for what they need to deploy in the future, and that FT is cloud-based.  Windows 10 Enterprise with Software Assurance is explicitly a VL plan to enable the migration forward for customers that have legacy licensing with Win10 eligibility. We don't need to make any changes to the SD as currently constructed."

Thanks for your feedback!

---ryan

**Comment by v-olduch** [comment]
Ok, so any VL plan is going to be supported with FastTrack? I think we should simply add the types of plans that are supported and for which workload.
