### ISSUE TITLE
Can't find documentation on Github

### ISSUE THREAD

**Issue by richardk2016** [MicrosoftDocs/OfficeDocs-FastTrack#12]
There is no content under https://github.com/MicrosoftDocs/OfficeDocs-FastTrack 
In other languages like German there is a fasttrack folder https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr.de-DE/tree/live/fasttrack. Where can I find the English documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1169b82d-73ea-0592-b293-60e7967c3911
* Version Independent ID: e3417a75-4993-f3af-6566-52b7d21680ac
* Content: [Onboarding and Migration Phases](https://docs.microsoft.com/en-us/fasttrack/o365-onboarding-and-migration#feedback)
* Content Source: [fasttrack/O365-onboarding-and-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/O365-onboarding-and-migration.md)
* Service: **o365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Richard,

I'm not sure I'm tracking the nature of your request. Would you please contact me directly at v-rberg@microsoft.com?
Thanks!
