### ISSUE TITLE
Sentence is wrong. (Extra word, "or"?)

### ISSUE THREAD

**Issue by Sherman8tor** [MicrosoftDocs/OfficeDocs-FastTrack#13]
Microsoft migrates any combination of the source environments listed below, each one at a time. We can migrate the onboarded messaging system using the FastTrack Center or if it's passed the FastTrack Center checks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52ab4b4-3255-78c5-9aa8-3cc0339ec570
* Version Independent ID: 720dc2ac-cc7b-528a-d3b3-1f90696e1fef
* Content: [Data Migration](https://docs.microsoft.com/en-us/fasttrack/O365-data-migration)
* Content Source: [fasttrack/O365-data-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/O365-data-migration.md)
* Service: **o365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Sherman8tor,

The use of "or" here is intentional. It's not erroneously used.
Thanks for your feedback!

**Comment by Sherman8tor** [comment]
That sentence does not make sense to me!
