### ISSUE TITLE
The Advanced eDiscovery section is wrong

### ISSUE THREAD

**Issue by mastood** [MicrosoftDocs/OfficeDocs-FastTrack#37]
It looks like we copied the O365 ATP section into the Advanced eDiscovery section.  We have the following listed for AeD

Advanced eDiscovery

- Enabling Safe Links, Safe Attachments, and anti-phishing.
- Configuring automation, investigation, and response.
- Using Attack Simulator.
- Reporting and threat analytics.

These have nothing to do with AeD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c0ab4-a229-c32d-b22b-28c00c9b1f74
* Version Independent ID: 3aeababc-42d6-f250-5b24-23eb7f353cc9
* Content: [Security and Compliance - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/z-scratch)
* Content Source: [fasttrack/z-scratch.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/z-scratch.md)
* GitHub Login: @rberg-steyer

**Comment by rberg-steyer** [comment]
Thanks for catching this! This has been addressed and will be changed for the 3/24/21 release.
