### ISSUE TITLE
Unable to access repo files

### ISSUE THREAD

**Issue by nikkelly** [MicrosoftDocs/OfficeDocs-FastTrack#38]
All of the files in this repo are missing/hidden from the public, making it much more difficult to suggest changes or submit a PR with the implemented changes. 

Not sure if this is intentional since almost all other MicrosoftDocs repos are fully available:
https://github.com/MicrosoftDocs/partner-center-sdk
https://github.com/MicrosoftDocs/Advertising-docs
https://github.com/MicrosoftDocs/azure-docs

Any links to repo source pages that are populated in the "Submit and view feedback for This page" results in a 404: https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/process-and-expectations.md

I'd love to contribute and submit some updates for documentation updates, but without access to the repo it removes a lot of the "openness" of open-source

**Comment by rberg-steyer** [comment]
Nik Kelly,

If you have feedback suggestions, please do the following:

1. Download a PDF of the SD content.
2. Convert the PDF into a Word doc.
3. Mark up the Word doc with your feedback (please ensure Track Changes is on and your feedback is flagged by comments to find it easier.
4. Provide an update here that you've done so.
I'll reach out to you at that point with next steps.
Please keep in mind that the Build PMs, CELA, and PMG for FastTrack have the final say on any updates. They may not agree with your feedback and it may not be incorporated.
Hope this helps!
