### ISSUE TITLE
Microsoft Teams support

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/OfficeDocs-FastTrack#39]
Microsoft Teams is now available on GCC High and DoD plans. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248cda6d-be44-c2ea-e20b-5d567953856c
* Version Independent ID: 501b682a-25b3-c23a-fd1f-4fd053676843
* Content: [Onboarding and Migration Phases for Office 365 US Government - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/us-gov-appendix-onboarding-and-migration#microsoft-teams)
* Content Source: [fasttrack/US-Gov-appendix-onboarding-and-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/US-Gov-appendix-onboarding-and-migration.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Carlos,

I've reached out to the Build PM about this. This change is in scope for a future release TBD. 
Thanks for this feedback!
