### ISSUE TITLE
Unkown Products

### ISSUE THREAD

**Issue by hisuzuki** [MicrosoftDocs/OfficeDocs-FastTrack#4]
What's Microsoft Advanced Threat Protection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f59014-c8c8-08e9-6304-d1d30f0fbda8
* Version Independent ID: 5317aa75-852e-14bc-0f17-8e3ad03349f7
* Content: [Eligible Services and Plans](https://docs.microsoft.com/en-us/fasttrack/m365-eligible-services-and-plans#feedback)
* Content Source: [fasttrack/M365-eligible-services-and-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/M365-eligible-services-and-plans.md)
* Service: **m365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by jimmuir** [comment]
Here is information about Advanced Threat Protection: https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp
