### ISSUE TITLE
Teams expectations

### ISSUE THREAD

**Issue by jongross4** [MicrosoftDocs/OfficeDocs-FastTrack#40]
States that Teams for government is not supported in GCC-H and DOD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41bb1da-59d1-357b-1a02-97b41fc26a08
* Version Independent ID: 64c451bb-4a4f-7d3a-e4c0-d2d76508e135
* Content: [Source Environment Expectations for Office 365 US Government - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/us-gov-appendix-source-environment-expectations)
* Content Source: [fasttrack/US-Gov-appendix-source-environment-expectations.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/US-Gov-appendix-source-environment-expectations.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Jon,

I've reached out to the Build PM about this. This change is in scope for a future release TBD. 
Thanks for this feedback!
