### ISSUE TITLE
Wrong information - Microsoft 365 Business Premium

### ISSUE THREAD

**Issue by danialonso** [MicrosoftDocs/OfficeDocs-FastTrack#41]
[Enter feedback here]
It shows "Microsoft 365 Business" in the old nomenclature and it is also badly categorized. It should be under "Microsoft 365 Business", not under "Enterprise".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility#eligible-plans)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Dani,

Can you please be more specific about where this is cited and why it should be changed? 
Thanks!

ryan
