### ISSUE TITLE
Broken link on Page

### ISSUE THREAD

**Issue by rauderson** [MicrosoftDocs/OfficeDocs-FastTrack#42]
The hyperlink in the first Note text block "For information on source environment expectations for Office 365 US Government, see **Source Environment Expectations for Office 365 US Government**." leads to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Link is now repaired. Thanks for the feedback!
