### ISSUE TITLE
Spelling Error in Defender for Endpoint Benefits

### ISSUE THREAD

**Issue by NoelFairclough** [MicrosoftDocs/OfficeDocs-FastTrack#43]
In the in-scope items for Microsoft Defender for Endpoint, in the last bullet point where it says "Onboarding and configuration of the following operating systems", the word "configuration" is mis-spelt.
![image](https://user-images.githubusercontent.com/48074808/133556277-31a3ddb6-c869-42db-9817-19d9513cf83a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 602b3c6f-5d1c-ba8b-ce81-fd73e994064a
* Version Independent ID: 66c2c38d-3cdf-3f6c-fdf6-5cd6ffd2f6f1
* Content: [FastTrack Center Benefit for Microsoft 365​ - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/introduction)
* Content Source: [fasttrack/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/introduction.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Thanks for pointing this out! It will be corrected with the 9/22 publication.
