### ISSUE TITLE
Lettering error in last bullet point of Defender for Endpoint

### ISSUE THREAD

**Issue by NoelFairclough** [MicrosoftDocs/OfficeDocs-FastTrack#44]
There is a capitalization error in the last bullet point of the "out of scope" items for Defender for Endpoint.  See attached image.

![image](https://user-images.githubusercontent.com/48074808/133557756-5c5ad7f0-7dee-438c-9de3-2b9aef30cde5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Thanks for pointing this out! It will be corrected with the 9/22 publication.
