### ISSUE TITLE
Missing M365 Business Premium License

### ISSUE THREAD

**Issue by jorge-ataide** [MicrosoftDocs/OfficeDocs-FastTrack#45]
The license plan "Microsoft 365 Business" under the Microsoft 365 Enterprise plans list does not exist and should be removed, it's incorrect.

Also, the "Microsoft 365 Business Premium", which is missing in the doc, should be added under the "Microsoft 365 Business" plans list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility#eligible-plans)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Jorge,

Can you please capture a screenshot of these items and mark them up the way you're asking for It will clarify your request and allow me to better validate the updates. Thanks!

**Comment by rberg-steyer** [comment]
Jorge,
This will be addressed in the 11/17 release.
Thanks for bringing it forward!
