### ISSUE TITLE
Exchange Source Environment Versions

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/OfficeDocs-FastTrack#46]
For [Products & Capabilities > Office 365 > Exchange Online](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities#office-365), Exchange 2003 is listed as viable source environment.

The [Data Migration > Source Environments section](https://docs.microsoft.com/en-us/fasttrack/data-migration#source-environments) lists Exchange 2010 as the minimum version for source environments.

It seems the first link should be updated from "Exchange 2003" to "Exchange 2010"?

Thank you,
tcfinney

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
TC, 
This will be updated in the 11/17 release. Thanks for bringing it forward!
