### ISSUE TITLE
Minor product name update needed, possibly grouping update too

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftDocs/OfficeDocs-FastTrack#48]
In the Microsoft 365 Enterprise section under Microsoft 365 plans it lists Microsoft 365 Business. 

This should be renamed to Microsoft 365 Business Premium and then moved under the Microsoft 365 Business section immediately below it.

The other name change is probably more of a timing issue as it is quite recent, but seeing that I'm providing feedback anyway - under Products and capabilities covered it has Microsoft Cloud App Security rather than Microsoft Defender for Cloud Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility#feedback)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Mark,

The first suggestion you made was approved for change in an earlier request and will go live on 11/17 (our scheduled release date).
The second suggestion you made will likely await alignment with other supported FastTrack collateral to occur simultaneously.
Thanks for reaching out!
