### ISSUE TITLE
IMAP migration does not support by FastTrack anymore.

### ISSUE THREAD

**Issue by bmt2499** [MicrosoftDocs/OfficeDocs-FastTrack#49]
IMAP migration does not support by FastTrack anymore. Please kindly check and update this document or at least mention "self-service support". It will make customers confused. Thank you.
Baramate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52ab4b4-3255-78c5-9aa8-3cc0339ec570
* Version Independent ID: 720dc2ac-cc7b-528a-d3b3-1f90696e1fef
* Content: [Data Migration - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/data-migration)
* Content Source: [fasttrack/data-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/data-migration.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Baramate, this is under review. Thanks for bringing it forward!

**Comment by rberg-steyer** [comment]
Baramate, this is in scope for change and will likely happen with the January publishing cadence. Thanks!
