### ISSUE TITLE
Content Sources (SHarpoint 2010) is outside scope

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-FastTrack#5]
Can we add more on sources that our outside of scope.  Its my understanding that SharePoint Server that is 2010 is outside of migration scope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52ab4b4-3255-78c5-9aa8-3cc0339ec570
* Version Independent ID: 720dc2ac-cc7b-528a-d3b3-1f90696e1fef
* Content: [Data Migration](https://docs.microsoft.com/en-us/fasttrack/o365-data-migration)
* Content Source: [fasttrack/O365-data-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/O365-data-migration.md)
* Service: **o365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Ramonin,

Can you please clarify what specifically you want updated? It will help us with any changes made.
Thanks!

**Comment by Ramonin** [comment]
Sorry can you please provide more contexnt.  I believe this is related to the migration scope for FasTrack Migration?  Not not sure
Can you provide a link to the content?  So I can refresh my memory this seems like it took a while for a response

Ramon Infante
Principal Program Manager Office 365 CXP
Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

For Office 365 Networking
https://aka.ms/O365Networking

For Office 365 ExpressRoute review process  - https://aka.ms/ErGuidance

For O365 network bandwidth meter
https://aka.ms/bandwidth

New Connectivity tool
http://connectivity.office.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fconnectivity.office.com&data=04%7C01%7CRamon.Infante%40microsoft.com%7Cbd37225ed6f24d1ae9d308d6b481b354%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894866485804492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=hl4ig5q9%2Bh7BsJU2rnFrF3KfrPzI9gRYxx9l3Wp%2Bk9I%3D&reserved=0>






[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]

**Comment by v-rberg-MSFT** [comment]
Ramonin,

You left your question at the bottom of this topic: https://docs.microsoft.com/en-us/fasttrack/o365-data-migration.
Do you still have a question?
Thanks!

**Comment by Ramonin** [comment]
Yes we need to be better about indicating what is out of scope as well.
SMB 1.0 is one
Sharepoint 2010 is another.

Ramon Infante
Principal Program Manager Office 365 CXP
Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

For Office 365 Networking
https://aka.ms/O365Networking

For Office 365 ExpressRoute review process  - https://aka.ms/ErGuidance

For O365 network bandwidth meter
https://aka.ms/bandwidth

New Connectivity tool
http://connectivity.office.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fconnectivity.office.com&data=04%7C01%7CRamon.Infante%40microsoft.com%7Cbd37225ed6f24d1ae9d308d6b481b354%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894866485804492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=hl4ig5q9%2Bh7BsJU2rnFrF3KfrPzI9gRYxx9l3Wp%2Bk9I%3D&reserved=0>






[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]

**Comment by v-rberg-MSFT** [comment]
Ramon,
Thanks for this feedback! I've consulted with our subject matter experts. As a rule, in the service description we try to define what’s in scope with the understanding that what isn’t listed should be considered out-of-scope. Please go to https://www.microsoft.com/en-us/fasttrack/ for more details.
