### ISSUE TITLE
Migration to SharePoint Online

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/OfficeDocs-FastTrack#50]
Over the last few weeks I was struggling with the supported source environments. Does the table underneath [Source environment details](https://docs.microsoft.com/en-us/fasttrack/data-migration#source-environment-details) by chance miss the various SharePoint On-Premises Versions?

There is a FastTrack repository within the Microsoft GitHub org, that holds various SharePoint Migration Tool and SharePoint Migration Assessment Tool Scripts. https://github.com/microsoft/FastTrack

Are they using SharePoint Migration Tool to migrate SharePoint On-Premises Environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52ab4b4-3255-78c5-9aa8-3cc0339ec570
* Version Independent ID: 720dc2ac-cc7b-528a-d3b3-1f90696e1fef
* Content: [Data Migration - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/data-migration#migration-to-sharepoint-online)
* Content Source: [fasttrack/data-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/data-migration.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Andi, this is being investigated. Thanks!

**Comment by rberg-steyer** [comment]
Andi, this is from a migration SME:

Over the last few weeks I was struggling with the supported source environments. Does the table underneath Source environment details by chance miss the various SharePoint On-Premises Versions?
**SME** The FastTrack Team doesn’t support the migration from SharePoint On-Premises to SharePoint Online (therefore this is NOT included there). 

There is a FastTrack repository within the Microsoft GitHub org, that holds various SharePoint Migration Tool and SharePoint Migration Assessment Tool Scripts. https://github.com/microsoft/FastTrack
Are they using SharePoint Migration Tool to migrate SharePoint On-Premises Environments?
**SME** No. FastTrack is not using SharePoint Migration tool (We do not support SharePoint Migration tool).   However, the tool is supported by Microsoft Support. So, customers can use SPMT to migrate towards SharePoint Online and can leverage Microsoft Support for any questions.
