### ISSUE TITLE
Cloud App Security has been renamed Defender for Cloud Apps.

### ISSUE THREAD

**Issue by dcurwin** [MicrosoftDocs/OfficeDocs-FastTrack#52]
Cloud App Security has been renamed Defender for Cloud Apps.

I'm responsible for Defender for Cloud Apps documentation. Feel free to be in contact with me if you have questions about the rebrand.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
David,

Please see the email I threaded you on with the SME driving this change. Let's track this request there going forward. Thanks!
