### ISSUE TITLE
Broken Link on Page

### ISSUE THREAD

**Issue by kbyrne11** [MicrosoftDocs/OfficeDocs-FastTrack#53]
Link for "complete the Customer Request for Modern Desktop Assessment form." opens a new page which states "Sorry, something went wrong
This form doesn't exist."

Thanks,
Kelli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/products-and-capabilities#feedback)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Kelli,

Thanks for identifying this! We're investigating it now. I'll keep you posted.

**Comment by rberg-steyer** [comment]
Kelli,

The link has been replaced and is now functional. Thanks again!

**Comment by rberg-steyer** [comment]
Kelli,

Can you please take screenshots of the link in question and the resulting page and then attach it your response?
Thanks!
