### ISSUE TITLE
Windows 11 licenses are not listed on eligibility plans

### ISSUE THREAD

**Issue by v-lochoa** [MicrosoftDocs/OfficeDocs-FastTrack#54]
[Enter feedback here]
Hi, 
On the eligible plans, it states: "You must purchase at least 150 licenses per tenant from one of the plans below to be eligible for FastTrack. The list is grouped by product family to help facilitate you finding the specific plans your company has purchased: Microsoft 365, Office 365, Enterprise Mobility & Security, and Windows 10." per my understanding this needs to be updated to show Windows 11 vs Windows 10.

Thanks,

Leslie Ochoa
FastTrack Manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Leslie,

This is being investigated.
I'll keep you posted.
Thanks!

**Comment by rberg-steyer** [comment]
Leslie,

This will be changed to reflect Windows 11 in the 4/20 release.
Thanks for your input!
