### ISSUE TITLE
M365 Government plan not included on FTC eligibility

### ISSUE THREAD

**Issue by v-lochoa** [MicrosoftDocs/OfficeDocs-FastTrack#55]
Hi,
Microsoft 365 U.S. Government plans are not mentioned on the eligibility plans page on the Playbook. My understanding is that these are included.

Thanks!

Leslie Ochoa
FastTrack Manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Leslie,

Playbook requests aren't handled though the service description. If this request deals with the service description, please capture the content in question in a screenshot to better clarify the issue.
Thanks!

**Comment by rberg-steyer** [comment]
Leslie
I'll contact you via email to continue this discussion.
Thanks!
