### ISSUE TITLE
Incorrect product name

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/OfficeDocs-FastTrack#59]
Please change Microsoft Information Governance to Data Lifecycle and Records Management.
https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-data-governance?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://docs.microsoft.com/en-us/fasttrack/eligibility)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Erica, 
We're currently in the middle of rebranding multiple items with the latest Purview branding. This should go live on 8/24. Please check for this suggestion then. If your suggestion wasn't in scope for that effort, please reach out here and we'll move forward accordingly. Thanks!
