### ISSUE TITLE
Eligibility for Non-profit / 501 (c)(3)

### ISSUE THREAD

**Issue by bill-p1** [MicrosoftDocs/OfficeDocs-FastTrack#6]
Can you please clarify FastTrack eligibility for organisations with 501 (c)(3) status, and non-profit organisations in countries **other** than the United States?

Are FastTrack services available if Microsoft products are acquired through programs like TechSoup?

Thank you...

**Comment by v-rberg-MSFT** [comment]
Hello.
Generally, if the organization is paying for their services and licenses, the products listed in the service description are available.
In terms of Tech Soup, the paid subscriptions would be eligible. See here for more: 

https://nam06.safelinks.protection.outlook.com/?url=https:%2F%2Fwww.techsoup.org%2Fproducts%2Foffice-365-%E2%80%93-nonprofit-cloud-subscriptions--G-49227--&data=01%7C01%7Cv-rberg%40microsoft.com%7C9317dc3aec644702116e08d6ca6e268e%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=tPx1GsxC%2FSVdMTdOmvRX4RpB%2FoXAiAbOyeXtrC4rYac%3D&reserved=0

Hope this helps!
