### ISSUE TITLE
Exchange Online Missing Info

### ISSUE THREAD

**Issue by DaleRNorman** [MicrosoftDocs/OfficeDocs-FastTrack#61]
Exchange Online out-of-scope information missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/fasttrack/products-and-capabilities)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Dale,
Can you be more specific and cite examples? Many of the O365 products also don't list out of scope items.
Thanks!

**Comment by DaleRNorman** [comment]
Hi,

Sure, no problem.  The Exchange Online section, I believe, used to contain a list of workloads that are out-of-scope for FastTrack (as the other sections contain).  This included tenant-to-tenant migrations, etc.  As a guide to the customer, we sometimes need this to confirm to a customer that we're able/not able to assist with requests.

Thanks,
Dale

**Comment by rberg-steyer** [comment]
Dale,
If you have a specific, clear list of bulleted items, I will bring them to the attention of the Build PM for Exchange Online and get their opinion. If you want to provide such a list, please send it to me directly: v-bermic. Thanks!
