### ISSUE TITLE
Does FastTrack still support Skype

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-FastTrack#62]
I believe this page is out of date. Please confirm if Skype is still supported and/or the appropriate services are listed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc991801-b044-6ee4-4e2b-8192c5eb2cba
* Version Independent ID: 6cf95be6-d873-1c0f-bfd5-1492d6617c85
* Content: [FastTrack Responsibilities for Office 365 US Government - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/fasttrack/us-gov-appendix-fasttrack-responsibilities)
* Content Source: [fasttrack/US-Gov-appendix-fasttrack-responsibilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/US-Gov-appendix-fasttrack-responsibilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by jimmuir** [comment]
Hello, thanks for your feedback on the FastTrack Service Description. Skype for Business was retired July 31, 2021. FastTrack supports enabling Skype for Business hybrid in order to deploy Teams but does not support configuration of Skype on-premises.
