### ISSUE TITLE
Links directly to each workload would be appreciated

### ISSUE THREAD

**Issue by sophieke815** [MicrosoftDocs/OfficeDocs-FastTrack#65]
Hi there, my name is Sophie Ke, and I'm the CxE Scale FastTrack PM for DLM/RM. I would like to provide feedback for this page.

Currently, we have bookmark links to the following main areas:

- General
- Security and Compliance
- Office 365
- Employee Experience
- Enterprise Mobility + Security
- Windows 11
- Windows 365 Enterprise
- Azure Virtual Desktop
- Universal Print
- App Assure
- Microsoft Edge
- Microsoft Surface

It would be easier to use and more user friendly if we could actually have bookmark links for each of the individual workloads, so that we can share the service description for each workload (example here for the licensing guide where we can link directly to the licensing requirement for DLM/RM: https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management). 

Many times, we need to send customers/internally what is in scope for a specific workload, and right now we can only send the link to "Security and Compliance" and then they would have to scroll to find the section they are looking for, which can be confusing.

Thanks,
Sophie

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d390cf53-1562-fef2-f1b9-570c81a8656b
* Version Independent ID: 6707d81c-c669-62fe-2c48-28de83052ec9
* Content: [Products and Capabilities - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/fasttrack/products-and-capabilities#security-and-compliance)
* Content Source: [fasttrack/products-and-capabilities.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/products-and-capabilities.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Sophie,
Thanks for this feedback! Back in 2020, the SD used to look and feel more like you're suggesting. It was redesigned the way it is now to better consolidate all the products into a single page. 
There's the possibility of another SD redesign happening in FY24, but it's still in the discussion phase at this point. 
Thanks again for reaching out!

**Comment by sophieke815** [comment]
Great, thank you for letting me know and reading my feedback.

If there is a redesign for FY24, I would love to offer this as feedback.

Thanks again,
Sophie

**Comment by rberg-steyer** [comment]
Sophie,
Will do.
Thanks again!
