### ISSUE TITLE
Typo "Teams Room devices"→"Teams Rooms devices"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-FastTrack#66]
https://learn.microsoft.com/en-us/fasttrack/us-gov-appendix-onboarding-and-migration
#PingMSFTDocs

![image](https://user-images.githubusercontent.com/40815708/235965486-823bbbe7-8c77-456f-bc73-4e94d86c5fc6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 248cda6d-be44-c2ea-e20b-5d567953856c
* Version Independent ID: 501b682a-25b3-c23a-fd1f-4fd053676843
* Content: [Onboarding and Migration Phases for Office 365 US Government - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/fasttrack/us-gov-appendix-onboarding-and-migration)
* Content Source: [fasttrack/US-Gov-appendix-onboarding-and-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/US-Gov-appendix-onboarding-and-migration.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Hiroshi,
This is now fixed. Thanks!
