### ISSUE TITLE
I appologize ..for my enthusiasm ..I didnt sing did i?

### ISSUE THREAD

**Issue by MitjaBene** [MicrosoftDocs/OfficeDocs-FastTrack#68]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 602b3c6f-5d1c-ba8b-ce81-fd73e994064a
* Version Independent ID: 66c2c38d-3cdf-3f6c-fdf6-5cd6ffd2f6f1
* Content: [FastTrack Center Benefit for Microsoft 365​ - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/fasttrack/introduction?culture=en-us&country=us)
* Content Source: [fasttrack/introduction.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/introduction.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Mitja,
Closing this as no feedback or actionable items provided.
