### ISSUE TITLE
doesn't cover tenant to tenant scenarios 

### ISSUE THREAD

**Issue by peterwww** [MicrosoftDocs/OfficeDocs-FastTrack#69]
this website does not explain situations such as e.g. .tenant to tenant migrations, do both tenants need to have 150 seats just one or maybe combined? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cbc4d5d-c873-4768-7244-642d893a874a
* Version Independent ID: fe1dd0e2-1e68-806f-4860-7fb0742645c1
* Content: [Eligibility - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/fasttrack/eligibility)
* Content Source: [fasttrack/eligibility.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/eligibility.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
Peter,
FastTrack doesn’t currently support tenant to tenant migrations, but we plan to in the future.
Thanks!
