### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jimmuir** [MicrosoftDocs/OfficeDocs-FastTrack#7]
ryan...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8837dbd-30e2-0129-0a98-9ff91a3764fa
* Version Independent ID: 0f8abaa1-6498-1e56-00a9-2b89aff46538
* Content: [FastTrack Center Benefit for Office 365](https://docs.microsoft.com/en-us/fasttrack/O365-fasttrack-benefit-for-office-365#feedback)
* Content Source: [fasttrack/O365-fasttrack-benefit-for-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/O365-fasttrack-benefit-for-office-365.md)
* Service: **o365-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Closing issue as a test of the system.
