### ISSUE TITLE
"fasttrack eligible partners"? 

### ISSUE THREAD

**Issue by almertes** [MicrosoftDocs/OfficeDocs-FastTrack#70]
Can we get a link to where we see a list of "fasttrack eligible partners"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e78b3b0a-9250-a3d5-bca3-7a251b1159e3
* Version Independent ID: 967ce1c7-efbc-2bfb-d140-a21e67140a66
* Content: [Process and Expectations - FastTrack – Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/fasttrack/process-and-expectations)
* Content Source: [fasttrack/process-and-expectations.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/process-and-expectations.md)
* Service: **o365-administration**
* GitHub Login: @rberg-steyer
* Microsoft Alias: **v-bermic**

**Comment by rberg-steyer** [comment]
This will be included in the next published version. Thanks for the suggestion!

**Comment by almertes** [comment]
[like]  Amber Mertes reacted to your message:
________________________________
