### ISSUE TITLE
Windows 10 link is circular (returns to the same base page)

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/OfficeDocs-FastTrack#8]
needs to be updated to https://docs.microsoft.com/en-us/fasttrack/win-10-windows-10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc295468-b4a6-91c8-74e3-a53974107787
* Version Independent ID: 4119ab9b-cfa6-caaa-8baf-9b11bc724563
* Content: [FastTrack Center Benefit for Windows 10](https://docs.microsoft.com/en-us/fasttrack/win-10-fasttrack-benefit-for-windows-10#feedback)
* Content Source: [fasttrack/Win-10-fasttrack-benefit-for-Windows-10.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/Win-10-fasttrack-benefit-for-Windows-10.md)
* Service: **windows-10-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by v-rberg-MSFT** [comment]
Fixed. Thanks!
