### ISSUE TITLE
Please add the exact build number of SCCM Needed to qualify

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-FastTrack#9]
We are getting question on what the SCCM exact build must be can you please add the minimum build number we need a customer to have to this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc8d4151-71a4-7aee-39f6-d5b78a925a4b
* Version Independent ID: 4a261055-f172-3be2-e1dd-dec0a3f7fc26
* Content: [Source Environment Expectations](https://docs.microsoft.com/en-us/fasttrack/win-10-source-environment-expectations)
* Content Source: [fasttrack/Win-10-source-environment-expectations.md](https://github.com/MicrosoftDocs/OfficeDocs-FastTrack-pr/blob/live/fasttrack/Win-10-source-environment-expectations.md)
* Service: **windows-10-administration**
* GitHub Login: @v-rberg-MSFT
* Microsoft Alias: **v-rberg**

**Comment by Ramonin** [comment]
The actual link is https://docs.microsoft.com/en-us/sccm/core/servers/manage/current-branch-versions-supported
Responded in Git hub.  We need to make discovey easier for customers this does not point to the direct link as indicated above.

Ramon Infante
Principal Program Manager
M365 and Secruity Group

Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

For Office 365 Networking
https://aka.ms/O365Networking

For Office 365 ExpressRoute review process  - https://aka.ms/ErGuidance

For O365 network bandwidth meter
https://aka.ms/bandwidth

New Connectivity tool
http://connectivity.office.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fconnectivity.office.com&data=04%7C01%7CRamon.Infante%40microsoft.com%7Cbd37225ed6f24d1ae9d308d6b481b354%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894866485804492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=hl4ig5q9%2Bh7BsJU2rnFrF3KfrPzI9gRYxx9l3Wp%2Bk9I%3D&reserved=0>



[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]

**Comment by v-rberg-MSFT** [comment]
Ramon,

The content discussed on the review email thread will be built into the 10/1/19 publishing.
Thanks!
